services:
  demo_mysql8:
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE: woori_design_web
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/config/:/docker-entrypoint-initdb.d/

volumes:
  mysql_data:
