server:
  port: 8081
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: back-woori-design-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/woori_design_web?allowPublicKeyRetrieval=true}
    username: ${db.username:root}
    password: ${db.password:root}
    hikari: # Hikari Pool, Connection Pool
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 100000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    #    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace